SpotifyVPY322/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Mvc;
using SpotifyVPY322.Repositories.Interfaces;

namespace SpotifyVPY322.Controllers;

public class AlbumController(IAlbumRepository albumRepository) : Controller
{
    public async Task<IActionResult> Index()
    {
        var album = await albumRepository.GetAllAsync();

        return View(album);
    }

    public async Task<IActionResult> Details(int id)
    {
        var detailsdAlbum = await albumRepository.GetDetailsAsync(id);

        return View(detailsdAlbum);
    }
}

SpotifyVPY322/Controllers/ArtistController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SpotifyVPY322.Dto.ArtistVM;
using SpotifyVPY322.Model;
using SpotifyVPY322.Repositories.Interfaces;

namespace SpotifyVPY322.Controllers;

public class ArtistController : Controller
{
    private IArtistRepository _artistRepository;
    private IGenreRepository _genreRepository;


    public ArtistController(IArtistRepository artistRepository, IGenreRepository genreRepository)
    {
        _artistRepository = artistRepository;
        _genreRepository = genreRepository;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var artists = await _artistRepository.GetAllAsync();

        return View(artists);
    }

    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        var artist = await _artistRepository.GetDetailsAsync(id);

        return View(artist);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        var genres = await _genreRepository.GetAllGenre();

        var createArtistVM = new CreateArtistVM
        {
            Title = string.Empty,
            PhotoUrl = string.Empty,
            Genre = string.Empty,
            Genres = new SelectList(genres)
        };

        return View(createArtistVM);
    }

    [HttpPost]
    public async Task<IActionResult> Create(
        [Bind(@$"{nameof(CreateArtistVM.Title)}, 
                 {nameof(CreateArtistVM.PhotoUrl)}, 
                 {nameof(CreateArtistVM.Genre)}")] 
        CreateArtistVM artistVM)
    {
        var genre = await _genreRepository.GetByTitle(artistVM.Genre);

        var artist = new Artist
        {
            Title = artistVM.Title,
            PhotoUrl = artistVM.PhotoUrl,
            Genre = genre
        };

        await _artistRepository.AddAsync(artist);

        var titleArtistController = nameof(ArtistController);
        var startIndexController = titleArtistController.IndexOf(nameof(Controller));
        var titleArtist = titleArtistController[..startIndexController];

        return RedirectToAction(nameof(Index), titleArtist);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var genres = await _genreRepository.GetAllGenre();

        var artist = await _artistRepository.GetByIdAsync(id);

        var updateArtistVM = new UpdateArtistVM
        {
            Id = id,
            Title = artist.Title,
            PhotoUrl = artist.PhotoUrl,
            Genre = string.Empty,
            Genres = new SelectList(genres)
        };

        return View(updateArtistVM);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(
        [Bind(@$"{nameof(UpdateArtistVM.Id)}, 
                 {nameof(CreateArtistVM.Title)}, 
                 {nameof(CreateArtistVM.PhotoUrl)},
                 {nameof(CreateArtistVM.Genre)}")]
        UpdateArtistVM updatedArtistVM)
    {
        var genre = await _genreRepository.GetByTitle(updatedArtistVM.Genre);

        var artist = new Artist
        {
            Id = updatedArtistVM.Id,
            Title = updatedArtistVM.Title,
            PhotoUrl = updatedArtistVM.PhotoUrl,
            Genre = genre
        };

        await _artistRepository.UpdateAsync(artist, genre);

        var titleArtistController = nameof(ArtistController);
        var startIndexController = titleArtistController.IndexOf(nameof(Controller));
        var titleArtist = titleArtistController[..startIndexController];

        return RedirectToAction(nameof(Index), titleArtist);
    }

    public async Task<IActionResult> Delete(int id)
    {
        await _artistRepository.DeleteByIdAsync(id);

        var titleArtistController = nameof(ArtistController);
        var startIndexController = titleArtistController.IndexOf(nameof(Controller));
        var titleArtist = titleArtistController[..startIndexController];

        return RedirectToAction(nameof(Index), titleArtist);
    }
}

SpotifyVPY322/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SpotifyVPY322.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

SpotifyVPY322/Views/Album/Details.cshtml
@using SpotifyVPY322.Model
@model Album

@if (Model is not null)
{
    <section class="h-100 h-custom" style="background-color: #eee;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col">
                    <div class="card">
                        <div class="card-body p-4">
                            <div class="row">
                                <div class="d-flex gap-5">
                                    <img src="https://avatars.yandex.net/get-music-content/5587254/4c9bd4b8.a.20509390-1/m1000x1000?webp=false" style="width: 250px" class="rounded float-start" alt="@Model.Title">
                                    <div>
                                        <h5 class="mb-3 text-body">
                                            Альбом @Model.Title
                                        </h5>
                                        <h5 class="mb-3 text-body">
    @*                                         Группы: @Model.Artist.Title *@
                                        </h5>
                                    </div>
                                </div>
                                <div class="col-lg-7 mt-3">
                                    @foreach (var song in Model.Songs)
                                    {
                                        <div class="card mb-3">
                                            <div class="card-body">
                                                <div class="d-flex justify-content-between">
                                                    <div class="d-flex flex-row align-items-center">
                                                        <div class="ms-3">
                                                            <h5>@song.Title</h5>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex flex-row align-items-center">
                                                        <audio controls src="@song.SongUrl"></audio>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

SpotifyVPY322/Views/Album/Index.cshtml
@using SpotifyVPY322.Dto.Album
@using SpotifyVPY322.Model

@model List<GetAllAlbumDto>
<div class="row">
    @foreach (var album in Model)
    {
        <div class="col-md-4">
            <div class="card album-card">
                <a asp-controller="Album" asp-action="Details" asp-route-id="@album.Id">
                    <img src="@album.PhotoUrl" class="card-img-top" alt="@album.Title">
                    <div class="card-body">
                        <h5 class="card-title">@album.Title</h5>
                    </div>
                </a>
            </div>
        </div>
    }
</div>

SpotifyVPY322/Views/Artist/Create.cshtml
@using SpotifyVPY322.Dto.ArtistVM
@using SpotifyVPY322.Model

@model CreateArtistVM

<form asp-action="Create">
    <div>
        <label>Title: </label>
        <input asp-for="Title">
    </div>
    <div>
        <label>PhotoUrl: </label>
        <input asp-for="PhotoUrl">
    </div>
    <div>
        <label>Genre: </label>
        <select asp-for="Genre" asp-items="Model.Genres"></select> 
    </div>
    <input type="submit" value="Добавить"/>
</form>

SpotifyVPY322/Views/Artist/Details.cshtml
@using SpotifyVPY322.Model
@model Artist

@if (Model is not null)
{
    <section class="h-100 h-custom" style="background-color: #eee;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col">
                    <div class="card">
                        <div class="card-body p-4">
                            <div class="row">
                                <div class="d-flex gap-5">
                                    <img src="@Model.PhotoUrl" style="width: 250px" class="rounded float-start" alt="@Model.Title">
                                    <div>
                                        <h5 class="mb-3 text-body">
                                            @Model.Title
                                        </h5>
                                    </div>
                                </div>
                                <div class="row">
                                    @foreach (var album in Model.Albums)
                                    {
                                        <div class="col-md-4">
                                            <div class="card album-card">
                                                <a asp-controller="Album" asp-action="Details" asp-route-id="@album.Id">
                                                    <img src="@album.PhotoUrl" class="card-img-top" alt="@album.Title">
                                                    <div class="card-body">
                                                        <h5 class="card-title">@album.Title</h5>
                                                    </div>
                                                </a>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

SpotifyVPY322/Views/Artist/Edit.cshtml
@using SpotifyVPY322.Dto.ArtistVM
@using SpotifyVPY322.Model

@model UpdateArtistVM

<form asp-action="Edit">
    <div>
        <input type="hidden" asp-for="Id">
    </div>
    <div>
        <label>Title: </label>
        <input asp-for="Title">
    </div>
    <div>
        <label>PhotoUrl: </label>
        <input asp-for="PhotoUrl">
    </div>
    <div>
        <label>Genre: </label>
        <select asp-for="Genre" asp-items="Model.Genres"></select>
    </div>
    <input type="submit" value="Отредактировать" />
</form>

SpotifyVPY322/Views/Artist/Index.cshtml
@using SpotifyVPY322.Dto.ArtistVM

@model List<GetAllArtistDto>

<div class="row">
    @foreach (var artist in Model)
    {
        <div class="col-md-4">
            <div class="card album-card">
                <a asp-controller="Artist" asp-action="Details" asp-route-id="@artist.Id">
                    <img src="@artist.PhotoUrl" class="card-img-top" alt="@artist.Title">
                    <div class="card-body">
                        <h5 class="card-title">@artist.Title</h5>
                    </div>
                </a>
                <a asp-controller="Artist"
                   asp-action="Delete"
                   asp-route-id="@artist.Id">Удалить</a>

                <a asp-controller="Artist"
                   asp-action="Edit"
                   asp-route-id="@artist.Id">Редактировать</a>
            </div>
        </div>
    }
</div>

SpotifyVPY322/Views/Home/Index.cshtml
<h1>Index</h1>

SpotifyVPY322/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Главная страница</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" a asp-controller="Album" asp-action="Index">Альбомы</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" a asp-controller="Artist" asp-action="Index">Артисты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        @RenderSection("Scripts", required: false)
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>